-- ====================================================================
-- SCRIPT SQL COMPLETO PARA SUPABASE (POSTGRESQL) - SPRING FASHION
-- Copia y pega todo este contenido directamente en el SQL Editor de Supabase
-- ====================================================================

-- 1. TABLA DE EVENTOS Y CONFIGURACIÓN GENERAL
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL DEFAULT 'Desfile Show / Sunset',
    tagline TEXT,
    date VARCHAR(50) NOT NULL,
    location VARCHAR(255) NOT NULL,
    hero_video_url TEXT,
    banner_url TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'activo',
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABLA DE NIVELES Y PRECIOS DE ENTRADAS (TIERS)
CREATE TABLE IF NOT EXISTS public.ticket_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    badge VARCHAR(50) DEFAULT 'General',
    price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    stock INTEGER NOT NULL DEFAULT 100,
    sold_count INTEGER NOT NULL DEFAULT 0,
    features_json TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABLA DE REGISTRO DE VENTAS DE ENTRADAS / COMPRADORES
CREATE TABLE IF NOT EXISTS public.ticket_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    buyer_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(50),
    tier_id BIGINT NOT NULL REFERENCES public.ticket_tiers(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(12, 2) NOT NULL,
    total_paid NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(50) DEFAULT 'MercadoPago',
    ticket_code VARCHAR(100) UNIQUE,
    qr_code TEXT,
    status VARCHAR(50) DEFAULT 'confirmado',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABLA DE RUBROS Y CATEGORÍAS OPERATIVAS
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(50) DEFAULT 'bi-tags',
    color VARCHAR(20) DEFAULT '#f59e0b',
    is_custom INTEGER DEFAULT 0
);

-- 5. TABLA DE STAFF, PROVEEDORES Y PRESUPUESTOS (GASTOS)
CREATE TABLE IF NOT EXISTS public.expenses_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    category_name VARCHAR(100) NOT NULL,
    provider_name VARCHAR(150) NOT NULL,
    contact VARCHAR(150),
    cost_agreed NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    is_paid INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABLA DE SPONSORS Y MARCAS ALIADAS
CREATE TABLE IF NOT EXISTS public.sponsors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    company_name VARCHAR(150) NOT NULL,
    contact_name VARCHAR(150),
    email VARCHAR(150),
    phone VARCHAR(50),
    tier VARCHAR(50) DEFAULT 'Gold',
    logo_url TEXT,
    website_url TEXT,
    proposal TEXT,
    status VARCHAR(50) DEFAULT 'aprobado',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. TABLA DE GALERÍA MULTIMEDIA (FOTOS Y VIDEOS)
CREATE TABLE IF NOT EXISTS public.gallery_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    title VARCHAR(150),
    media_type VARCHAR(20) DEFAULT 'image',
    category VARCHAR(50) DEFAULT 'desfile',
    media_url TEXT NOT NULL,
    thumbnail_url TEXT,
    is_featured INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. TABLA DE RESEÑAS DE COMUNIDAD Y LEADS DE MAILING
CREATE TABLE IF NOT EXISTS public.feedback_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    comment_text TEXT NOT NULL,
    rating INTEGER NOT NULL DEFAULT 5,
    avatar_url TEXT,
    edition_tag VARCHAR(50) DEFAULT 'Edición Anterior',
    is_approved INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. TABLA DE ROADMAP SECUENCIAL DE PRODUCCIÓN
CREATE TABLE IF NOT EXISTS public.roadmap_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    step_order INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    is_completed INTEGER NOT NULL DEFAULT 0,
    is_unlocked INTEGER NOT NULL DEFAULT 0,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. TABLA DE USUARIOS ADMINISTRADORES
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role VARCHAR(50) DEFAULT 'superadmin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- POLÍTICAS DE ACCESO ROW LEVEL SECURITY (RLS) PARA SUPABASE
-- ====================================================================
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sponsors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roadmap_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública para la landing
DROP POLICY IF EXISTS "Public Events Read" ON public.events;
CREATE POLICY "Public Events Read" ON public.events FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Tiers Read" ON public.ticket_tiers;
CREATE POLICY "Public Tiers Read" ON public.ticket_tiers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Sponsors Read" ON public.sponsors;
CREATE POLICY "Public Sponsors Read" ON public.sponsors FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Gallery Read" ON public.gallery_media;
CREATE POLICY "Public Gallery Read" ON public.gallery_media FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Feedback Read" ON public.feedback_comments;
CREATE POLICY "Public Feedback Read" ON public.feedback_comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Roadmap Read" ON public.roadmap_steps;
CREATE POLICY "Public Roadmap Read" ON public.roadmap_steps FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Categories Read" ON public.categories;
CREATE POLICY "Public Categories Read" ON public.categories FOR SELECT USING (true);

-- Políticas de inserción pública (Checkout de entradas, Sponsors B2B y Feedback)
DROP POLICY IF EXISTS "Public Insert Sales" ON public.ticket_sales;
CREATE POLICY "Public Insert Sales" ON public.ticket_sales FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Insert Feedback" ON public.feedback_comments;
CREATE POLICY "Public Insert Feedback" ON public.feedback_comments FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Insert Sponsors" ON public.sponsors;
CREATE POLICY "Public Insert Sponsors" ON public.sponsors FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Insert Provider Application" ON public.expenses_providers;
CREATE POLICY "Public Insert Provider Application" ON public.expenses_providers FOR INSERT WITH CHECK (true);

-- Acceso completo para usuarios autenticados / servicio backend
DROP POLICY IF EXISTS "Admin Full Events" ON public.events;
CREATE POLICY "Admin Full Events" ON public.events FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin Full Tiers" ON public.ticket_tiers;
CREATE POLICY "Admin Full Tiers" ON public.ticket_tiers FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin Full Sales" ON public.ticket_sales;
CREATE POLICY "Admin Full Sales" ON public.ticket_sales FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin Full Expenses" ON public.expenses_providers;
CREATE POLICY "Admin Full Expenses" ON public.expenses_providers FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin Full Sponsors" ON public.sponsors;
CREATE POLICY "Admin Full Sponsors" ON public.sponsors FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin Full Gallery" ON public.gallery_media;
CREATE POLICY "Admin Full Gallery" ON public.gallery_media FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin Full Feedback" ON public.feedback_comments;
CREATE POLICY "Admin Full Feedback" ON public.feedback_comments FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin Full Roadmap" ON public.roadmap_steps;
CREATE POLICY "Admin Full Roadmap" ON public.roadmap_steps FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin Full Categories" ON public.categories;
CREATE POLICY "Admin Full Categories" ON public.categories FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin Full Users" ON public.admin_users;
CREATE POLICY "Admin Full Users" ON public.admin_users FOR ALL USING (true);

-- ====================================================================
-- POBLADO DE DATOS INICIALES (SEED DATA)
-- ====================================================================

-- 1. Usuario Administrador (admin / tu_password encriptada con Bcrypt)
INSERT INTO public.admin_users (username, password_hash, role)
VALUES ('admin', '$2a$10$Hwt.iXZVQTn7DCsNi3SIQ.93StF5yua15iXfm.GwjHwzDT1JaDq2y', 'superadmin')
ON CONFLICT (username) DO NOTHING;

-- 2. Evento Principal Spring Fashion 2026
INSERT INTO public.events (id, title, type, tagline, date, location, hero_video_url, banner_url, status, description)
VALUES (
    1,
    'Spring Fashion 2026',
    'Desfile Show / Sunset',
    'Donde la alta costura se fusiona con el atardecer, la música electrónica de vanguardia y el networking exclusivo.',
    '2026-11-21T17:30:00',
    'Bodega & Viñedos Monteviejo, Valle de Uco, Mendoza',
    'https://assets.mixkit.co/videos/preview/mixkit-models-walking-on-a-runway-at-a-fashion-show-41846-large.mp4',
    'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1920&q=80',
    'activo',
    'Una experiencia multisensorial única que reúne a diseñadores de renombre, modelos de alta costura, DJs internacionales, gastronomía de autor maridada con vinos de bodega boutique y un espacio de coworking/networking para marcas y creadores.'
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    type = EXCLUDED.type,
    tagline = EXCLUDED.tagline,
    location = EXCLUDED.location,
    hero_video_url = EXCLUDED.hero_video_url;

-- 3. Categorías Operativas de Rubros
INSERT INTO public.categories (name, icon, color, is_custom) VALUES
('DJ / Música en vivo', 'bi-music-note-beamed', '#ec4899', 0),
('Sonido, Luces y Pantallas LED', 'bi-lightning-charge-fill', '#8b5cf6', 0),
('Artistas de show y Modelos', 'bi-stars', '#f59e0b', 0),
('Fotógrafos y Realizadores Audiovisuales', 'bi-camera-reels-fill', '#06b6d4', 0),
('Stands de trabajo / Activaciones', 'bi-shop', '#10b981', 0),
('Seguridad y Control de accesos', 'bi-shield-lock-fill', '#ef4444', 0),
('Catering / Barras y Vinos', 'bi-cup-straw', '#6366f1', 0),
('Sponsors y Marcas aliadas', 'bi-gem', '#eab308', 0)
ON CONFLICT (name) DO NOTHING;

-- 4. Pases y Tiers de Entradas
INSERT INTO public.ticket_tiers (event_id, name, badge, price, stock, sold_count, features_json, is_active) VALUES
(1, 'Sunset Early Pass', 'Preventa Limitada', 18500.00, 250, 84, '["Acceso al predio desde las 17:30 hs","Degustación de bienvenida (2 copas de vino boutique)","Acceso a zona Sunset & Escenario Principal","Acceso a sector Foodtrucks Gourmet y Barra Libre de agua"]', 1),
(1, 'VIP Runway Experience', 'Más Elegido', 34000.00, 150, 62, '["Ubicación preferencial Front-Row en la Pasarela","Copa de espumante ilimitada durante el desfile","Acceso exclusivo a Networking & Sunset Lounge","Gift Bag oficial Spring Fashion 2026","Fast Pass en ingresos y barras"]', 1),
(1, 'Backstage & All Access Pass', 'Acceso Total', 58000.00, 50, 28, '["Acceso ilimitado a Backstage, Model Prep y Sala de Diseñadores","Catering gourmet maridado en 4 pasos por Chef invitado","Open Bar premium durante todo el evento","Meet & Greet con Speakers, Diseñadores y DJs","Estacionamiento VIP vigilado incluido"]', 1),
(1, 'Lounge Table Ultra VIP (6 Personas)', 'Mesa Exclusiva', 260000.00, 12, 5, '["Mesa reservada en altura con vista panorámica a pasarela y sunset","2 Botellas de Champagne Francés + 3 Vinos Reserva de Bodega","Tabla de degustación premium fría y caliente para 6","Camarero y personal de seguridad dedicado","Acceso total a todas las zonas del evento"]', 1);

-- 5. Hoja de Ruta Secuencial de Producción
INSERT INTO public.roadmap_steps (event_id, step_order, title, description, is_completed, is_unlocked, completed_at) VALUES
(1, 1, 'Paso 1: Definición de Fecha, Formato y Locación', 'Reserva confirmada en Bodega Monteviejo (Valle de Uco), habilitaciones municipales y seguro de evento.', 1, 1, NOW()),
(1, 2, 'Paso 2: Creación de Contenido Promocional y Media Kit', 'Diseño de identidad visual Spring Fashion, videos teaser, catálogo de sponsors y apertura de preventa.', 1, 1, NOW()),
(1, 3, 'Paso 3: Lanzamiento de Preventa y Captación de Sponsors', 'Apertura de la plataforma de tickets al público general, acuerdos B2B y confirmación de stands.', 0, 1, NULL),
(1, 4, 'Paso 4: Confirmación Técnica, Artistas y Pasarela', 'Rider técnico de sonido, pantallas LED, confirmación de 24 modelos de alta costura y DJs.', 0, 0, NULL),
(1, 5, 'Paso 5: Minuto a Minuto, Montaje Logístico y Desfile', 'Montaje de pasarela, prueba de luces al atardecer, acreditación digital y apertura de puertas.', 0, 0, NULL);

-- 6. Presupuesto, Staff y Proveedores Iniciales
INSERT INTO public.expenses_providers (event_id, category_name, provider_name, contact, cost_agreed, is_paid, notes) VALUES
(1, 'DJ / Música en vivo', 'DJ Julian Black (Melodic Techno Live)', '+54 9 261 455-8891', 750000.00, 1, 'Seña 50% abonada, incluye rider'),
(1, 'Sonido, Luces y Pantallas LED', 'Lumina Stage Pro Rentals', 'contacto@luminastage.com', 1850000.00, 1, 'Pantallas LED P3 curvas + audio Line Array'),
(1, 'Artistas de show y Modelos', 'Agencia Élite Runway Models (20 Modelos)', 'booking@eliterunway.com', 1200000.00, 0, 'Vestuario, peinado y maquillaje incluidos'),
(1, 'Fotógrafos y Realizadores Audiovisuales', 'Sunset Film Studio (Foto & Video 4K Drone)', 'martin@sunsetfilm.ar', 480000.00, 1, 'Cobertura en vivo + aftermovie 48hs'),
(1, 'Seguridad y Control de accesos', 'Vanguard Security Privada (12 efectivos)', 'operaciones@vanguardsec.com', 520000.00, 0, 'Control de molinetes y zona VIP'),
(1, 'Catering / Barras y Vinos', 'Gourmet Bodega Catering & Cocktails', 'maridaje@gourmetbodega.com', 1450000.00, 0, 'Degustación y barra de bienvenida'),
(1, 'Stands de trabajo / Activaciones', 'Creative Decor & Ambientaciones', 'hola@creativedecor.com', 380000.00, 1, 'Lounge coworking y sector photocall');

-- 7. Sponsors Iniciales
INSERT INTO public.sponsors (event_id, company_name, contact_name, email, tier, logo_url, proposal, status) VALUES
(1, 'Vogue & Style Magazine', 'Valeria Rossi', 'alianzas@voguestyle.com', 'Platinum', 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=300&q=80', 'Cobertura editorial y stand central de tendencias', 'aprobado'),
(1, 'Bodega Monteviejo Vinos', 'Ignacio Larrea', 'marketing@monteviejo.com', 'Platinum', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=300&q=80', 'Sponsor oficial de vinos y maridajes en el Sunset', 'aprobado'),
(1, 'Aura Cosmética & Skincare', 'Camila Peña', 'camilap@aurabeauty.com', 'Gold', 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=300&q=80', 'Gifting para asistentes VIP y retoques en backstage', 'aprobado'),
(1, 'Lexus Motors Experience', 'Federico Gómez', 'fgomez@lexus-exp.com', 'Gold', 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=300&q=80', 'Exhibición de vehículo híbrido de lujo en el ingreso', 'aprobado'),
(1, 'Radio Sunset Beats FM', 'Sol Morales', 'produccion@sunsetbeats.fm', 'Media Partner', 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=300&q=80', 'Transmisión vía streaming y notas en vivo', 'aprobado');

-- 8. Galería Multimedia Inicial
INSERT INTO public.gallery_media (event_id, title, media_type, category, media_url, thumbnail_url, is_featured) VALUES
(1, 'Pasarela Principal Alta Costura', 'image', 'desfile', 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80', 1),
(1, 'Sunset & Vinos en Viñedos', 'image', 'sunset', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80', 1),
(1, 'Backstage & Styling Exclusivo', 'image', 'backstage', 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=1200&q=80', 1),
(1, 'Coctelería de Autor & Gastronomía', 'image', 'gastronomia', 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1200&q=80', 1),
(1, 'Golden Hour Runway Show', 'image', 'desfile', 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80', 1),
(1, 'Live Performance & Sunset Beats', 'image', 'sunset', 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80', 1),
(1, 'Lounge & Networking VIP', 'image', 'backstage', 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80', 1),
(1, 'Aftermovie Oficial Teaser', 'video', 'aftermovie', 'https://assets.mixkit.co/videos/preview/mixkit-models-walking-on-a-runway-at-a-fashion-show-41846-large.mp4', 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=600&q=80', 1);

-- 9. Reseñas y Testimonios Aprobados para el Carrusel de 5s
INSERT INTO public.feedback_comments (user_name, email, comment_text, rating, avatar_url, edition_tag, is_approved) VALUES
('Florencia Benítez', 'florencia.b@gmail.com', 'La edición anterior fue sencillamente deslumbrante. El desfile al atardecer entre los viñedos con la música en vivo te transporta por completo. ¡Ya tengo mis entradas para este año!', 5, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80', 'Edición Sunset 2025', 1),
('Matías Cavalieri', 'matias.cava@techbrands.io', 'Como sponsor y asistente del sector VIP, la calidad de los contactos y la experiencia de networking superaron cualquier expectativa. Una puesta en escena de nivel internacional.', 5, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80', 'Edición Sunset 2025', 1),
('Luciana Morales', 'luciana.fashion@outlook.com', 'Los diseños presentados en pasarela y el maridaje de vinos estuvieron a la altura de las grandes capitales de la moda. La energía del cierre con los DJs es inolvidable.', 5, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80', 'Edición Runway 2025', 1),
('Esteban Rivas', 'esteban.rivas@creativegroup.com', 'Impecable organización, puntualidad en los accesos y el sonido acústico al aire libre fue perfecto. Felicitaciones a todo el equipo de producción.', 5, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80', 'Edición Sunset 2025', 1);

-- 10. Ventas Iniciales de Tickets
INSERT INTO public.ticket_sales (event_id, buyer_name, email, phone, tier_id, quantity, unit_price, total_paid, payment_method, ticket_code, qr_code, status) VALUES
(1, 'Agustina Mendonça', 'agustina.m@gmail.com', '+5492614881122', 1, 2, 18500.00, 37000.00, 'MercadoPago', 'SF-A91X', 'SPRINGFASHION:2026:CODE:SF-A91X', 'confirmado'),
(1, 'Rodrigo Peralta', 'rperalta@estudioperalta.com', '+5491147728833', 2, 2, 34000.00, 68000.00, 'Tarjeta Crédito/Débito', 'SF-B42Z', 'SPRINGFASHION:2026:CODE:SF-B42Z', 'confirmado'),
(1, 'Sofía Von Wernich', 'sofia.vw@luxurybrands.com', '+5491158839922', 3, 1, 58000.00, 58000.00, 'Transferencia Bancaria', 'SF-C77K', 'SPRINGFASHION:2026:CODE:SF-C77K', 'confirmado'),
(1, 'Grupo Inversor Los Andes', 'eventos@inversorlosandes.com', '+5492614992211', 4, 1, 260000.00, 260000.00, 'Transferencia Bancaria', 'SF-D99W', 'SPRINGFASHION:2026:CODE:SF-D99W', 'confirmado');
