-- ====================================================================
-- MIGRACIÓN SUPABASE: ACTUALIZACIÓN COMPLETA (SPLIT LINKS, QR SCANNER Y TIERS)
-- Ejecuta este script en el SQL Editor de Supabase (https://spbxwnfddizbqddqbrht.supabase.co)
-- ====================================================================

-- 1. Tabla de Promotores / Vendedores / RRPP con slug para enlaces amigables (/lucas)
CREATE TABLE IF NOT EXISTS public.promoters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT DEFAULT 1 REFERENCES public.events(id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(50),
    promo_code VARCHAR(50) UNIQUE NOT NULL,
    slug VARCHAR(100) UNIQUE,
    split_code VARCHAR(100),
    commission_percentage NUMERIC(5, 2) NOT NULL DEFAULT 10.00,
    total_sales_count INTEGER NOT NULL DEFAULT 0,
    total_commission_earned NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Añadir campos para afiliados, control de QR y escaneo de acceso en ticket_sales
ALTER TABLE public.ticket_sales ADD COLUMN IF NOT EXISTS promoter_id BIGINT REFERENCES public.promoters(id);
ALTER TABLE public.ticket_sales ADD COLUMN IF NOT EXISTS promoter_code VARCHAR(50);
ALTER TABLE public.ticket_sales ADD COLUMN IF NOT EXISTS split_code VARCHAR(100);
ALTER TABLE public.ticket_sales ADD COLUMN IF NOT EXISTS dlocal_payment_id VARCHAR(100);
ALTER TABLE public.ticket_sales ADD COLUMN IF NOT EXISTS dlocal_redirect_url TEXT;
ALTER TABLE public.ticket_sales ADD COLUMN IF NOT EXISTS is_used INTEGER DEFAULT 0;
ALTER TABLE public.ticket_sales ADD COLUMN IF NOT EXISTS used_at TIMESTAMPTZ;

-- 3. Añadir estado editable a ticket_tiers (activa, agotada, oculta)
ALTER TABLE public.ticket_tiers ADD COLUMN IF NOT EXISTS tier_status VARCHAR(50) DEFAULT 'activa';
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'ARS';

-- 4. Habilitar RLS y políticas
ALTER TABLE public.promoters ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Active Promoters" ON public.promoters;
CREATE POLICY "Public Read Active Promoters" ON public.promoters FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin Full Promoters" ON public.promoters;
CREATE POLICY "Admin Full Promoters" ON public.promoters FOR ALL USING (true);

-- 5. Actualizar o insertar vendedores de prueba con enlaces amigables (/lucas, /sofia)
INSERT INTO public.promoters (event_id, name, email, phone, promo_code, slug, split_code, commission_percentage, total_sales_count, total_commission_earned)
VALUES 
(1, 'Lucas Gómez (RRPP)', 'lucas.gomez@springpromoters.com', '+54 9 261 555-0199', 'LUCAS2026', 'lucas', 'c5BsnXQ6NR==', 10.00, 4, 13600.00),
(1, 'Sofía Valenzuela (Influencer)', 'sofia.valenzuela@influencers.ar', '+54 9 11 4400-8811', 'SOFIAVIP', 'sofia', 'c3BsaXQ6NA==', 15.00, 2, 10200.00)
ON CONFLICT (promo_code) DO UPDATE SET slug = EXCLUDED.slug, split_code = EXCLUDED.split_code;
