-- ====================================================================
-- SPRING FASHION 2026 - ESQUEMA COMPLETO PARA SUPABASE (POSTGRESQL)
-- ====================================================================
-- Copia y pega todo este código en el SQL Editor de tu proyecto en Supabase.
-- Incluye todas las tablas, columnas, credenciales dLocal Go y 1 ejemplo limpio por sección.

-- 1. TABLA DE EVENTOS Y CONFIGURACIÓN GENERAL
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL DEFAULT 'Spring Fashion 2026',
    type VARCHAR(100) NOT NULL DEFAULT 'Desfile Show / Sunset',
    tagline TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT '2026-11-21 17:30:00-03',
    location VARCHAR(255) NOT NULL DEFAULT 'Bodega & Viñedos Monteviejo, Valle de Uco, Mendoza',
    currency VARCHAR(10) DEFAULT 'ARS',
    hero_video_url TEXT,
    banner_url TEXT,
    status VARCHAR(50) DEFAULT 'activo',
    description TEXT,
    show_experiences INTEGER DEFAULT 1,
    show_lineup INTEGER DEFAULT 1,
    mediakit_file_url TEXT,
    mediakit_download_link TEXT,
    dlocal_env VARCHAR(50) DEFAULT 'production',
    dlocal_api_key TEXT,
    dlocal_api_secret TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. TABLA DE TIPOS DE ENTRADAS / TANDAS DINÁMICAS
CREATE TABLE IF NOT EXISTS ticket_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    badge VARCHAR(100) DEFAULT 'General',
    price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    stock INTEGER NOT NULL DEFAULT 100,
    sold_count INTEGER NOT NULL DEFAULT 0,
    features_json JSONB DEFAULT '[]'::jsonb,
    tier_status VARCHAR(50) DEFAULT 'activa',
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. TABLA DE PROMOTORES / VENDEDORES / RRPP (SPLIT PAYMENTS)
CREATE TABLE IF NOT EXISTS promoters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(100),
    promo_code VARCHAR(100) UNIQUE NOT NULL,
    slug VARCHAR(100) UNIQUE,
    split_code VARCHAR(255),
    commission_percentage NUMERIC(5, 2) DEFAULT 10.00,
    total_sales_count INTEGER DEFAULT 0,
    total_commission_earned NUMERIC(12, 2) DEFAULT 0.00,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. TABLA DE VENTAS DE ENTRADAS / TICKETS / ESCÁNER QR
CREATE TABLE IF NOT EXISTS ticket_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    buyer_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(100),
    tier_id BIGINT REFERENCES ticket_tiers(id) ON DELETE SET NULL,
    quantity INTEGER DEFAULT 1,
    unit_price NUMERIC(12, 2) NOT NULL,
    total_paid NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(100) DEFAULT 'dLocal Go',
    ticket_code VARCHAR(100) UNIQUE NOT NULL,
    qr_code TEXT,
    promoter_id BIGINT REFERENCES promoters(id) ON DELETE SET NULL,
    promoter_code VARCHAR(100),
    split_code VARCHAR(255),
    dlocal_payment_id VARCHAR(255),
    dlocal_redirect_url TEXT,
    is_used INTEGER DEFAULT 0,
    used_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(50) DEFAULT 'confirmado',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. TABLA DE RUBROS / CATEGORÍAS DE GASTOS
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    icon VARCHAR(100) DEFAULT 'bi-tags',
    color VARCHAR(50) DEFAULT '#f59e0b',
    is_custom INTEGER DEFAULT 0
);

-- 6. TABLA DE PROVEEDORES, STAFF Y PRESUPUESTOS
CREATE TABLE IF NOT EXISTS expenses_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    category_name VARCHAR(255) NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    contact VARCHAR(255),
    cost_agreed NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    is_paid INTEGER DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. TABLA DE EXPERIENCIAS MULTISENSORIALES
CREATE TABLE IF NOT EXISTS event_experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(100) DEFAULT 'bi-stars',
    image_url TEXT,
    sort_order INTEGER DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. TABLA DE TALENTO & LINEUP / SPEAKERS Y ARTISTAS INVITADOS
CREATE TABLE IF NOT EXISTS event_artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    role_title VARCHAR(255) NOT NULL,
    category VARCHAR(100) DEFAULT 'diseñador',
    bio TEXT,
    image_url TEXT,
    instagram_url TEXT,
    sort_order INTEGER DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. TABLA DE SPONSORS Y MARCAS PATROCINADORAS
CREATE TABLE IF NOT EXISTS sponsors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    company_name VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(100),
    tier VARCHAR(100) DEFAULT 'Platinum',
    logo_url TEXT,
    website_url TEXT,
    proposal TEXT,
    status VARCHAR(50) DEFAULT 'aprobado',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 10. TABLA DE GALERÍA MULTIMEDIA
CREATE TABLE IF NOT EXISTS gallery_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    title VARCHAR(255),
    media_type VARCHAR(50) DEFAULT 'image',
    category VARCHAR(100) DEFAULT 'desfile',
    media_url TEXT NOT NULL,
    thumbnail_url TEXT,
    is_featured INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 11. TABLA DE FEEDBACK / RESEÑAS DE LA COMUNIDAD
CREATE TABLE IF NOT EXISTS feedback_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    comment_text TEXT NOT NULL,
    rating INTEGER DEFAULT 5,
    avatar_url TEXT,
    edition_tag VARCHAR(100) DEFAULT 'Edición Anterior',
    is_approved INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 12. TABLA DE ROADMAP DE PRODUCCIÓN
CREATE TABLE IF NOT EXISTS roadmap_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    step_order INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    is_completed INTEGER DEFAULT 0,
    is_unlocked INTEGER DEFAULT 0,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 13. TABLA DE ADMINISTRADORES
CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'superadmin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ====================================================================
-- SEED DATA LIMPIO: 1 EJEMPLO POR SECCIÓN (LISTO PARA PRODUCCIÓN)
-- ====================================================================

-- 1. Evento Principal con credenciales dLocal Go de Producción
INSERT INTO events (
    id, title, type, tagline, date, location, currency, hero_video_url, banner_url, 
    status, description, show_experiences, show_lineup, dlocal_env, dlocal_api_key, dlocal_api_secret
) VALUES (
    1,
    'Spring Fashion 2026',
    'Desfile Show / Sunset',
    'Donde la alta costura se fusiona con el atardecer, la música electrónica de vanguardia y el networking exclusivo.',
    '2026-11-21 17:30:00-03',
    'Bodega & Viñedos Monteviejo, Valle de Uco, Mendoza',
    'ARS',
    'https://assets.mixkit.co/videos/preview/mixkit-models-walking-on-a-runway-at-a-fashion-show-41846-large.mp4',
    'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1920&q=80',
    'activo',
    'Una experiencia multisensorial única que reúne a diseñadores de renombre, modelos de alta costura, DJs internacionales, gastronomía de autor maridada con vinos de bodega boutique y un espacio de coworking/networking para marcas y creadores.',
    1,
    1,
    'production',
    'TU_DLOCAL_API_KEY',
    'TU_DLOCAL_API_SECRET'
) ON CONFLICT (id) DO UPDATE SET 
    dlocal_env = 'production',
    dlocal_api_key = 'TU_DLOCAL_API_KEY',
    dlocal_api_secret = 'TU_DLOCAL_API_SECRET';

-- 2. Administrador inicial por defecto (Configura tu contraseña segura en .env)
INSERT INTO admin_users (id, username, password_hash, role)
VALUES (1, 'admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'superadmin')
ON CONFLICT (username) DO NOTHING;

-- 3. Pase de Entrada (1 Ejemplo Limpio)
INSERT INTO ticket_tiers (id, event_id, name, badge, price, stock, sold_count, features_json, tier_status, is_active)
VALUES (
    1, 1, 'Pase General - Early Bird', 'Preventa Exclusiva', 25000.00, 200, 0,
    '["Acceso general al desfile show y pasarela", "Copa de bienvenida de Bodega Monteviejo", "Acceso al sector Sunset y música en vivo", "Voucher digital con código QR de acreditación"]'::jsonb,
    'activa', 1
) ON CONFLICT (id) DO NOTHING;

-- 4. Experiencia Multisensorial (1 Ejemplo Limpio)
INSERT INTO event_experiences (id, event_id, title, description, icon, image_url, sort_order, is_active)
VALUES (
    1, 1, 'Alta Costura & Runway Show',
    '24 modelos en pasarela exhibiendo colecciones exclusivas de diseñadores al atardecer.',
    'bi-stars',
    'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
    1, 1
) ON CONFLICT (id) DO NOTHING;

-- 5. Artista / Speaker Invitado (1 Ejemplo Limpio)
INSERT INTO event_artists (id, event_id, name, role_title, category, bio, image_url, instagram_url, sort_order, is_active)
VALUES (
    1, 1, 'Camila Rossi', 'Diseñadora de Alta Costura', 'diseñador',
    'Referente de la moda de autor con colecciones de vanguardia presentadas en pasarelas internacionales.',
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    'https://instagram.com', 1, 1
) ON CONFLICT (id) DO NOTHING;

-- 6. Sponsor (1 Ejemplo Limpio)
INSERT INTO sponsors (id, event_id, company_name, contact_name, email, tier, logo_url, website_url, proposal, status)
VALUES (
    1, 1, 'Bodega Monteviejo', 'Ignacio Larrea', 'marketing@monteviejo.com', 'Platinum',
    'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=300&q=80',
    'https://bodegamonteviejo.com', 'Locación oficial y maridaje de vinos de alta gama', 'aprobado'
) ON CONFLICT (id) DO NOTHING;

-- 7. Promotor / Vendedor (Enlace directo /lucas)
INSERT INTO promoters (id, event_id, name, email, phone, promo_code, slug, split_code, commission_percentage, total_sales_count, total_commission_earned, is_active)
VALUES (
    1, 1, 'Lucas Gómez (RRPP)', 'lucas@springpromoters.com', '+54 9 261 555-0199',
    'LUCAS2026', 'lucas', 'c5BsnXQ6NR==', 10.00, 0, 0.00, 1
) ON CONFLICT (promo_code) DO NOTHING;

-- 8. Rubro y Proveedor (1 Ejemplo Limpio)
INSERT INTO categories (id, name, icon, color, is_custom)
VALUES (1, 'Sonido, Luces y Pantallas LED', 'bi-lightning-charge-fill', '#8b5cf6', 0)
ON CONFLICT (name) DO NOTHING;

INSERT INTO expenses_providers (id, event_id, category_name, provider_name, contact, cost_agreed, is_paid, notes)
VALUES (
    1, 1, 'Sonido, Luces y Pantallas LED', 'AudioStage Pro Rentals', '+54 9 261 455-8891', 180000.00, 0, 'Seña 50% acordada'
) ON CONFLICT (id) DO NOTHING;

-- 9. Galería (1 Ejemplo Limpio)
INSERT INTO gallery_media (id, event_id, title, media_type, category, media_url, thumbnail_url, is_featured)
VALUES (
    1, 1, 'Pasarela Principal al Atardecer', 'image', 'desfile',
    'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=600&q=80', 1
) ON CONFLICT (id) DO NOTHING;

-- 10. Testimonio / Feedback (1 Ejemplo Limpio)
INSERT INTO feedback_comments (id, user_name, email, comment_text, rating, avatar_url, edition_tag, is_approved)
VALUES (
    1, 'Florencia Benítez', 'florencia.b@gmail.com',
    'Una experiencia inigualable que combina moda de alta costura, música de primer nivel y un atardecer inolvidable.',
    5, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    'Edición Anterior', 1
) ON CONFLICT (id) DO NOTHING;

-- 11. Roadmap Secuencial (6 Pasos)
INSERT INTO roadmap_steps (event_id, step_order, title, description, is_completed, is_unlocked, completed_at) VALUES
(1, 1, 'Definición de Fecha, Formato y Locación', 'Confirmación de locación en Bodega Monteviejo y habilitaciones.', 1, 1, now()),
(1, 2, 'Creación de Identidad Visual y Media Kit', 'Lanzamiento de identidad, catálogo B2B y apertura de plataforma.', 1, 1, now()),
(1, 3, 'Lanzamiento de Preventa y Captación de Sponsors', 'Venta de entradas con dLocal Go y acuerdos con marcas aliadas.', 0, 1, NULL),
(1, 4, 'Confirmación Técnica, Artistas y Pasarela', 'Rider de iluminación, sonido, 24 modelos y line-up musical.', 0, 0, NULL),
(1, 5, 'Montaje, Desfile Show y Acreditaciones', 'Apertura de puertas con escáner QR y ejecución del desfile.', 0, 0, NULL)
ON CONFLICT (id) DO NOTHING;
